name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Android
      run: ./gradlew :composeApp:assembleRelease
    - name: Build Desktop
      run: ./gradlew :composeApp:createReleaseDistributable
    - name: Release nightly
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: Latest
        tag: latest
        files: |
          composeApp/build/outputs/apk/release/*.apk
          composeApp/build/compose/binaries/main-release/msi/*.msi
        fail_on_unmatched_files: true
